=== DenisseC02/WordPress_ApiTesting/wp_api/resources/data/schemas/blocks/read_block_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "date": {
      "type": "string"
    },
    "date_gmt": {
      "type": "string"
    },
    "guid": {
      "type": "object",
      "properties": {
        "rendered": {
          "type": "string"
        }
      },
      "required": [
        "rendered"
      ]
    },
    "modified": {
      "type": "string"
    },
    "modified_gmt": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "link": {
      "type": "string"
    },
    "title": {
      "type": "object",
      "properties": {
        "raw": {
          "type": "string"
        }
      },
      "required": [
        "raw"
      ]
    },
    "content": {
      "type": "object",
      "properties": {
        "raw": {
          "type": "string"
        },
        "protected": {
          "type": "boolean"
        }
      },
      "required": [
        "raw",
        "protected"
      ]
    },
    "template": {
      "type": "string"
    },
    "_links": {
      "type": "object",
      "properties": {
        "self": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "href": {
                  "type": "string"
                }
              },
              "required": [
                "href"
              ]
            }
          ]
        },
        "collection": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "href": {
                  "type": "string"
                }
              },
              "required": [
                "href"
              ]
            }
          ]
        },
        "about": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "href": {
                  "type": "string"
                }
              },
              "required": [
                "href"
              ]
            }
          ]
        },
        "version-history": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "count": {
                  "type": "integer"
                },
                "href": {
                  "type": "string"
                }
              },
              "required": [
                "count",
                "href"
              ]
            }
          ]
        },
        "wp:attachment": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "href": {
                  "type": "string"
                }
              },
              "required": [
                "href"
              ]
            }
          ]
        },
        "curies": {
          "type": "array",
          "items": [
            {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "href": {
                  "type": "string"
                },
                "templated": {
                  "type": "boolean"
                }
              },
              "required": [
                "name",
                "href",
                "templated"
              ]
            }
          ]
        }
      },
      "required": [
        "self",
        "collection",
        "about",
        "version-history",
        "wp:attachment",
        "curies"
      ]
    }
  },
  "required": [
    "id",
    "date",
    "date_gmt",
    "guid",
    "modified",
    "modified_gmt",
    "slug",
    "status",
    "type",
    "link",
    "title",
    "content",
    "template",
    "_links"
  ]
}

=== DenisseC02/WordPress_ApiTesting/wp_api/resources/data/schemas/read_block_response.json
{
    "id": 20,
    "date": "2023-04-19T06:37:33",
    "date_gmt": "2023-04-19T06:37:33",
    "guid": {
      "rendered": "http://localhost/index.php/2023/04/19/my-block-rogerpp-8/"
    },
    "modified": "2023-04-19T06:37:33",
    "modified_gmt": "2023-04-19T06:37:33",
    "slug": "my-block-rogerpp-8",
    "status": "publish",
    "type": "wp_block",
    "link": "http://localhost/index.php/2023/04/19/my-block-rogerpp-8/",
    "title": {
      "raw": "My Block rogerpp"
    },
    "content": {
      "raw": "[my-blockpp]",
      "protected": false
    },
    "template": "",
    "_links": {
      "self": [
        {
          "href": "http://localhost/index.php/wp-json/wp/v2/blocks/20"
        }
      ],
      "collection": [
        {
          "href": "http://localhost/index.php/wp-json/wp/v2/blocks"
        }
      ],
      "about": [
        {
          "href": "http://localhost/index.php/wp-json/wp/v2/types/wp_block"
        }
      ],
      "version-history": [
        {
          "count": 0,
          "href": "http://localhost/index.php/wp-json/wp/v2/blocks/20/revisions"
        }
      ],
      "wp:attachment": [
        {
          "href": "http://localhost/index.php/wp-json/wp/v2/media?parent=20"
        }
      ],
      "curies": [
        {
          "name": "wp",
          "href": "https://api.w.org/{rel}",
          "templated": true
        }
      ]
    }
  }
